# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: notes-api-secret
type: Opaque
data:
  DB_USER: cm9vdA== # base64 encoded value for 'root'
  DB_PASSWORD: cGFzc3dvcmQxMjM= # base64 encoded value for 'password123'