# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: notes-api-secret
type: Opaque
data:
  mongodb-uri: bW9uZ29kYitzcnY6Ly80NHZpa2FzcmpwdXQ0NDpQWTFMTmNGSVk0ekhGSDdUQGFwaS1jbHVzdGVyLnQydnlzLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1BUEktY2x1c3Rlcg==   # base64 encoded value for 'password123'