# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
spec:
  selector:
    app: notes-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
